trigger:
  - cimdata

stages:
- stage: Linux
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job: Build
      steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: false
            mavenOptions: '-Xmx3072m -Dmaven.test.failure.ignore=true'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: 1.17
            jdkArchitectureOption: 'x64'

        - script: ls -laR $(Pipeline.Workspace)
          displayName: 'Display Workspace Files after Maven run'

        - task: PublishBuildArtifacts@1
          displayName: 'Publishing jar Artifact'
          inputs:
            PathtoPublish: '$(Pipeline.Workspace)/s/MSGViewer/target/msgviewer.jar'
            ArtifactName: 'msgviewer jar'
            publishLocation: 'Container'

        - script: mkdir $(Build.Repository.LocalPath)/output
          displayName: 'Make Output Directory'

        - script: cp $(Pipeline.Workspace)/s/MSGViewer/target/cdMsgViewer.exe $(Build.Repository.LocalPath)/output/cdMsgViewer.exe
          displayName: 'Copy .exe file to output'

        - script: cp -R $(Pipeline.Workspace)/s/cimdata/jre $(Build.Repository.LocalPath)/output/
          displayName: 'Copy jre from cimdata folder file to output'

        - task: ArchiveFiles@2
          displayName: 'Archive output artifacts'
          inputs:
            rootFolderOrFile: 'output'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/msgviewer.zip
            replaceExistingArchive: false

        - task: PublishBuildArtifacts@1
          displayName: 'Publishing zip Artifact'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/msgviewer.zip'
            ArtifactName: 'msgviewer zip'
            publishLocation: 'Container'

- stage: Windows
  pool:
    vmImage: 'windows-latest'
  jobs:
    - job: Build
      steps:
        - script: |
            start /WAIT $(Build.Repository.LocalPath)\MsgViewer_setup\build_setup.cmd
          displayName: 'Building Setup for cdMsgViewer'

        - task: PublishBuildArtifacts@1
          displayName: 'Publishing Setup Artifacts'
          inputs:
            PathtoPublish: '$(Build.Repository.LocalPath)\MsgViewer_setup\bin\release\cdMsgViewer_setup.exe'
            ArtifactName: 'cdMsgViewer_setup'
            publishLocation: 'Container'#