trigger:
  - cimdata

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: false
      mavenOptions: '-Xmx3072m -Dmaven.test.failure.ignore=true'
      javaHomeOption: 'JDKVersion'
      jdkArchitectureOption: 'x64'

  - script: ls -laR $(Pipeline.Workspace)
    displayName: 'Display Workspace Files after Maven run'

  - script: mkdir $(Build.Repository.LocalPath)/output
    displayName: 'Make Output Directory'

  - script: cp $(Pipeline.Workspace)/s/MSGViewer/target/cdMsgViewer.exe $(Build.Repository.LocalPath)/output/cdMsgViewer.exe
    displayName: 'Copy .exe file to output'

  - script: cp -R $(Pipeline.Workspace)/s/cimdata/jre $(Build.Repository.LocalPath)/output/
    displayName: 'Copy jre from cimdata folder file to output'

  - task: ArchiveFiles@2
    displayName: 'Archive output artifacts'
    inputs:
      rootFolderOrFile: 'output'
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/msgviewer.zip
      replaceExistingArchive: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publishing Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/msgviewer.zip'
      ArtifactName: 'msgviewer'
      publishLocation: 'Container'